[package]
name = "rustonance"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
reqwest = { version= "0.11", features = ["stream"] }
serenity = "0.12.2"
songbird = "0.4.3"
tokio = { version = "1.39.2", features = ["full"] }
